### ISSUE TITLE
Add automatic versioning 

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/free-Web3-resources#94]
Add a release.yml file in the workflows directory, with the content below

Release will also create a tag and show on the homepage of the repo

Disclaimer: will need to use conventional commit messages to trigger release creation

File path `.github/workflows/release.yml`

 ```yaml
name: Releases
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './package.json,./package-lock.json'

      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
```

<img width="670" alt="Screenshot 2022-09-30 at 16 17 40" src="https://user-images.githubusercontent.com/624760/193302433-4fc8c0a3-ebb5-4e11-aeae-609fbfe00dbc.png">
